/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-10 at 13:54:51 UTC 
 * Modify at your own risk.
 */

package com.appspot.yuanx_sharepoint_viewer.sharepointviewer.model;

/**
 * Model definition for Comment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the sharepointviewer. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Comment extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("add_date")
  private String addDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String entityKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("from_user_key")
  private String fromUserKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("from_user_nickname")
  private String fromUserNickname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String message;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("sharepoint_key")
  private String sharepointKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("to_user_key")
  private String toUserKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("to_user_nickname")
  private String toUserNickname;

  /**
   * @return value or {@code null} for none
   */
  public String getAddDate() {
    return addDate;
  }

  /**
   * @param addDate addDate or {@code null} for none
   */
  public Comment setAddDate(String addDate) {
    this.addDate = addDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getEntityKey() {
    return entityKey;
  }

  /**
   * @param entityKey entityKey or {@code null} for none
   */
  public Comment setEntityKey(String entityKey) {
    this.entityKey = entityKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getFromUserKey() {
    return fromUserKey;
  }

  /**
   * @param fromUserKey fromUserKey or {@code null} for none
   */
  public Comment setFromUserKey(String fromUserKey) {
    this.fromUserKey = fromUserKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getFromUserNickname() {
    return fromUserNickname;
  }

  /**
   * @param fromUserNickname fromUserNickname or {@code null} for none
   */
  public Comment setFromUserNickname(String fromUserNickname) {
    this.fromUserNickname = fromUserNickname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMessage() {
    return message;
  }

  /**
   * @param message message or {@code null} for none
   */
  public Comment setMessage(String message) {
    this.message = message;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSharepointKey() {
    return sharepointKey;
  }

  /**
   * @param sharepointKey sharepointKey or {@code null} for none
   */
  public Comment setSharepointKey(String sharepointKey) {
    this.sharepointKey = sharepointKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getToUserKey() {
    return toUserKey;
  }

  /**
   * @param toUserKey toUserKey or {@code null} for none
   */
  public Comment setToUserKey(String toUserKey) {
    this.toUserKey = toUserKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getToUserNickname() {
    return toUserNickname;
  }

  /**
   * @param toUserNickname toUserNickname or {@code null} for none
   */
  public Comment setToUserNickname(String toUserNickname) {
    this.toUserNickname = toUserNickname;
    return this;
  }

  @Override
  public Comment set(String fieldName, Object value) {
    return (Comment) super.set(fieldName, value);
  }

  @Override
  public Comment clone() {
    return (Comment) super.clone();
  }

}
