/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-16 at 12:21:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model;

/**
 * Model definition for DishCollection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the aramarkHelperMenuFetcher. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DishCollection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Dish> items;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String nextPageToken;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Dish> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public DishCollection setItems(java.util.List<Dish> items) {
    this.items = items;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getNextPageToken() {
    return nextPageToken;
  }

  /**
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  public DishCollection setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public DishCollection set(String fieldName, Object value) {
    return (DishCollection) super.set(fieldName, value);
  }

  @Override
  public DishCollection clone() {
    return (DishCollection) super.clone();
  }

}
