/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-16 at 12:21:25 UTC 
 * Modify at your own risk.
 */

package com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher;

/**
 * Service definition for AramarkHelperMenuFetcher (v1).
 *
 * <p>
 * Menu Fetcher API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AramarkHelperMenuFetcherRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class AramarkHelperMenuFetcher extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.20.0 of the aramarkHelperMenuFetcher library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://aramark-helper-menu-fetcher.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "aramarkHelperMenuFetcher/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public AramarkHelperMenuFetcher(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  AramarkHelperMenuFetcher(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Category collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code AramarkHelperMenuFetcher aramarkHelperMenuFetcher = new AramarkHelperMenuFetcher(...);}
   *   {@code AramarkHelperMenuFetcher.Category.List request = aramarkHelperMenuFetcher.category().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Category category() {
    return new Category();
  }

  /**
   * The "category" collection of methods.
   */
  public class Category {

    /**
     * Create a request for the method "category.list".
     *
     * This request holds the parameters needed by the aramarkHelperMenuFetcher server.  After setting
     * any optional parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @param parent
     * @return the request
     */
    public List list(String parent) throws java.io.IOException {
      List result = new List(parent);
      initialize(result);
      return result;
    }

    public class List extends AramarkHelperMenuFetcherRequest<com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.CategoryCollection> {

      private static final String REST_PATH = "category/list/{parent}";

      /**
       * Create a request for the method "category.list".
       *
       * This request holds the parameters needed by the the aramarkHelperMenuFetcher server.  After
       * setting any optional parameters, call the {@link List#execute()} method to invoke the remote
       * operation. <p> {@link
       * List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param parent
       * @since 1.13
       */
      protected List(String parent) {
        super(AramarkHelperMenuFetcher.this, "GET", REST_PATH, null, com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.CategoryCollection.class);
        this.parent = com.google.api.client.util.Preconditions.checkNotNull(parent, "Required parameter parent must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private String parent;

      /**

       */
      public String getParent() {
        return parent;
      }

      public List setParent(String parent) {
        this.parent = parent;
        return this;
      }

      @com.google.api.client.util.Key
      private String pageToken;

      /**

       */
      public String getPageToken() {
        return pageToken;
      }

      public List setPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
      }

      @com.google.api.client.util.Key
      private Long limit;

      /**

       */
      public Long getLimit() {
        return limit;
      }

      public List setLimit(Long limit) {
        this.limit = limit;
        return this;
      }

      @com.google.api.client.util.Key
      private String order;

      /**

       */
      public String getOrder() {
        return order;
      }

      public List setOrder(String order) {
        this.order = order;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Dish collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code AramarkHelperMenuFetcher aramarkHelperMenuFetcher = new AramarkHelperMenuFetcher(...);}
   *   {@code AramarkHelperMenuFetcher.Dish.List request = aramarkHelperMenuFetcher.dish().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Dish dish() {
    return new Dish();
  }

  /**
   * The "dish" collection of methods.
   */
  public class Dish {

    /**
     * Create a request for the method "dish.list".
     *
     * This request holds the parameters needed by the aramarkHelperMenuFetcher server.  After setting
     * any optional parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @param parent
     * @return the request
     */
    public List list(String parent) throws java.io.IOException {
      List result = new List(parent);
      initialize(result);
      return result;
    }

    public class List extends AramarkHelperMenuFetcherRequest<com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.DishCollection> {

      private static final String REST_PATH = "dish/list/{parent}";

      /**
       * Create a request for the method "dish.list".
       *
       * This request holds the parameters needed by the the aramarkHelperMenuFetcher server.  After
       * setting any optional parameters, call the {@link List#execute()} method to invoke the remote
       * operation. <p> {@link
       * List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param parent
       * @since 1.13
       */
      protected List(String parent) {
        super(AramarkHelperMenuFetcher.this, "GET", REST_PATH, null, com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.DishCollection.class);
        this.parent = com.google.api.client.util.Preconditions.checkNotNull(parent, "Required parameter parent must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private String parent;

      /**

       */
      public String getParent() {
        return parent;
      }

      public List setParent(String parent) {
        this.parent = parent;
        return this;
      }

      @com.google.api.client.util.Key
      private String pageToken;

      /**

       */
      public String getPageToken() {
        return pageToken;
      }

      public List setPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
      }

      @com.google.api.client.util.Key
      private Long limit;

      /**

       */
      public Long getLimit() {
        return limit;
      }

      public List setLimit(Long limit) {
        this.limit = limit;
        return this;
      }

      @com.google.api.client.util.Key
      private String order;

      /**

       */
      public String getOrder() {
        return order;
      }

      public List setOrder(String order) {
        this.order = order;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Period collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code AramarkHelperMenuFetcher aramarkHelperMenuFetcher = new AramarkHelperMenuFetcher(...);}
   *   {@code AramarkHelperMenuFetcher.Period.List request = aramarkHelperMenuFetcher.period().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Period period() {
    return new Period();
  }

  /**
   * The "period" collection of methods.
   */
  public class Period {

    /**
     * Create a request for the method "period.list".
     *
     * This request holds the parameters needed by the aramarkHelperMenuFetcher server.  After setting
     * any optional parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @param selectDate
     * @return the request
     */
    public List list(String selectDate) throws java.io.IOException {
      List result = new List(selectDate);
      initialize(result);
      return result;
    }

    public class List extends AramarkHelperMenuFetcherRequest<com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.PeriodCollection> {

      private static final String REST_PATH = "period/list/{selectDate}";

      /**
       * Create a request for the method "period.list".
       *
       * This request holds the parameters needed by the the aramarkHelperMenuFetcher server.  After
       * setting any optional parameters, call the {@link List#execute()} method to invoke the remote
       * operation. <p> {@link
       * List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
       * called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param selectDate
       * @since 1.13
       */
      protected List(String selectDate) {
        super(AramarkHelperMenuFetcher.this, "GET", REST_PATH, null, com.appspot.aramark_helper_menu_fetcher.aramarkHelperMenuFetcher.model.PeriodCollection.class);
        this.selectDate = com.google.api.client.util.Preconditions.checkNotNull(selectDate, "Required parameter selectDate must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private String selectDate;

      /**

       */
      public String getSelectDate() {
        return selectDate;
      }

      public List setSelectDate(String selectDate) {
        this.selectDate = selectDate;
        return this;
      }

      @com.google.api.client.util.Key
      private String pageToken;

      /**

       */
      public String getPageToken() {
        return pageToken;
      }

      public List setPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
      }

      @com.google.api.client.util.Key
      private Long limit;

      /**

       */
      public Long getLimit() {
        return limit;
      }

      public List setLimit(Long limit) {
        this.limit = limit;
        return this;
      }

      @com.google.api.client.util.Key
      private String order;

      /**

       */
      public String getOrder() {
        return order;
      }

      public List setOrder(String order) {
        this.order = order;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link AramarkHelperMenuFetcher}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link AramarkHelperMenuFetcher}. */
    @Override
    public AramarkHelperMenuFetcher build() {
      return new AramarkHelperMenuFetcher(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AramarkHelperMenuFetcherRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAramarkHelperMenuFetcherRequestInitializer(
        AramarkHelperMenuFetcherRequestInitializer aramarkhelpermenufetcherRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(aramarkhelpermenufetcherRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
